Repository dailydevops/healthchecks, pull requests merged in 2025-06, with the labels that each got.

#750 test: Added test environment for wsl remote testing
  testEnvironments.json
Labels: state:ready for merge, type:chore

#753 chore(ci): Add Publish flag
  .github/workflows/cicd.yml
Labels: state:ready for merge, type:chore

#751 feat: Added support for MongoDb (Testcontainer v4.4.0)
  Directory.Packages.props
  HealthChecks.sln
  src/NetEvolve.HealthChecks.MongoDb/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.MongoDb/MongoDbConfigure.cs
  src/NetEvolve.HealthChecks.MongoDb/MongoDbHealthCheck.cs
  src/NetEvolve.HealthChecks.MongoDb/MongoDbOptions.cs
  src/NetEvolve.HealthChecks.MongoDb/NetEvolve.HealthChecks.MongoDb.csproj
  src/NetEvolve.HealthChecks.MongoDb/README.md
  tests/NetEvolve.HealthChecks.Tests.Architecture/HealthCheckArchitecture.cs
  tests/NetEvolve.HealthChecks.Tests.Architecture/NetEvolve.HealthChecks.Tests.Architecture.csproj
  tests/NetEvolve.HealthChecks.Tests.Integration/MongoDb/MongoDbDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/MongoDb/MongoDbHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/NetEvolve.HealthChecks.Tests.Integration.csproj
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseConfigration_ConnectionStringEmpty_ShouldThrowException.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseConfigration_TimeoutMinusTwo_ShouldThrowException.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseConfigurationWithKeyedService_Healthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseConfigurationWithKeyedService_ShouldReturnHealthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseConfiguration_Degraded.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseConfiguration_Healthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseConfiguration_ShouldReturnDegraded.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseConfiguration_ShouldReturnHealthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseOptionsWithKeyedService_Healthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseOptionsWithKeyedService_ShouldReturnHealthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseOptions_Degraded.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseOptions_Healthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseOptions_ShouldReturnDegraded.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseOptions_ShouldReturnHealthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseOptions_ShouldReturnUnhealthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/MongoDbHealthCheck.AddMongoDb_UseOptions_Unhealthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/NetEvolve.HealthChecks.MongoDb.PublicApi_HasNotChanged_Theory.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Unit/MongoDb/DependencyInjectionExtensionsTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/MongoDb/MongoDbConfigureTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/MongoDb/MongoDbHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/MongoDb/MongoDbOptionsTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/NetEvolve.HealthChecks.Tests.Unit.csproj
Labels: state:ready for merge, type:feature

#761 fix: Stabilization of tests, Healthy tests now use a timeout of 1s as…
  tests/NetEvolve.HealthChecks.Tests.Integration/AWS/SNS/SimpleNotificationServiceHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Apache/ActiveMq/ActiveMqHealthCheckBaseTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure/Blobs/BlobContainerAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure/Blobs/BlobServiceAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure/Queues/QueueClientAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure/Queues/QueueServiceAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure/ServiceBus/ServiceBusQueueHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure/ServiceBus/ServiceBusSubscriptionHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure/ServiceBus/ServiceBusTopicHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure/Tables/TableClientAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/ClickHouse/ClickHouseHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/MySql/MySqlHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/MySqlConnector/MySqlConnectorHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Npgsql/NpgsqlHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Redis/RedisHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/SQLite/SQLiteHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/SqlServer/SqlServerHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/SqlServerLegacy/SqlServerLegacyHealthCheckTests.cs
Labels: state:ready for merge, type:bug

#765 fix(deps): Added missing package reference to `NetEvolve.HealthChecks…
  src/NetEvolve.HealthChecks.RavenDb/NetEvolve.HealthChecks.RavenDb.csproj
Labels: state:ready for merge, type:bug

#767 fix: Reworked static ClientCreation Method for Azure.Queues
  src/NetEvolve.HealthChecks.Azure.Queues/ClientCreation.cs
  src/NetEvolve.HealthChecks.Azure.Queues/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Azure.Queues/QueueClientAvailableHealthCheck.cs
  src/NetEvolve.HealthChecks.Azure.Queues/QueueServiceAvailableHealthCheck.cs
Labels: state:ready for merge, type:architectural runway

#766 fix: Reworked static ClientCreation Method for `Azure.Blobs`
  src/NetEvolve.HealthChecks.Azure.Blobs/BlobContainerAvailableHealthCheck.cs
  src/NetEvolve.HealthChecks.Azure.Blobs/BlobServiceAvailableHealthCheck.cs
  src/NetEvolve.HealthChecks.Azure.Blobs/ClientCreation.cs
  src/NetEvolve.HealthChecks.Azure.Blobs/DependencyInjectionExtensions.cs
Labels: state:ready for merge, type:architectural runway

#776 feat: Implementation of `NetEvolve.HealthChecks.DuckDB`
  Directory.Packages.props
  HealthChecks.sln
  src/NetEvolve.HealthChecks.DuckDB/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.DuckDB/DuckDBConfigure.cs
  src/NetEvolve.HealthChecks.DuckDB/DuckDBHealthCheck.cs
  src/NetEvolve.HealthChecks.DuckDB/DuckDBOptions.cs
  src/NetEvolve.HealthChecks.DuckDB/NetEvolve.HealthChecks.DuckDB.csproj
  src/NetEvolve.HealthChecks.DuckDB/README.md
  tests/NetEvolve.HealthChecks.Tests.Architecture/HealthCheckArchitecture.cs
  tests/NetEvolve.HealthChecks.Tests.Architecture/NetEvolve.HealthChecks.Tests.Architecture.csproj
  tests/NetEvolve.HealthChecks.Tests.Integration/DuckDB/DuckDBHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/NetEvolve.HealthChecks.Tests.Integration.csproj
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/DuckDBHealthCheck.AddDuckDB_UseConfigration_ConnectionStringEmpty_ThrowException.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/DuckDBHealthCheck.AddDuckDB_UseConfigration_TimeoutMinusTwo_ThrowException.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/DuckDBHealthCheck.AddDuckDB_UseConfiguration_Degraded.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/DuckDBHealthCheck.AddDuckDB_UseConfiguration_Healthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/DuckDBHealthCheck.AddDuckDB_UseOptions_Degraded.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/DuckDBHealthCheck.AddDuckDB_UseOptions_Healthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/DuckDBHealthCheck.AddDuckDB_UseOptions_Unhealthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/NetEvolve.HealthChecks.DuckDB.PublicApi_HasNotChanged_Theory.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Unit/DuckDB/DependencyInjectionExtensionsTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/DuckDB/DuckDBConfigureTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/DuckDB/DuckDBHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/DuckDB/DuckDBOptionsTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/NetEvolve.HealthChecks.Tests.Unit.csproj
Labels: state:ready for merge, type:feature

#774 chore: Updated .NET Version in READMEs
  src/NetEvolve.HealthChecks.AWS.SNS/README.md
  src/NetEvolve.HealthChecks.Abstractions/README.md
  src/NetEvolve.HealthChecks.Apache.ActiveMq/README.md
  src/NetEvolve.HealthChecks.Apache.Kafka/README.md
  src/NetEvolve.HealthChecks.Azure.Blobs/README.md
  src/NetEvolve.HealthChecks.Azure.Queues/README.md
  src/NetEvolve.HealthChecks.Azure.ServiceBus/README.md
  src/NetEvolve.HealthChecks.Azure.Tables/README.md
  src/NetEvolve.HealthChecks.ClickHouse/README.md
  src/NetEvolve.HealthChecks.Dapr/README.md
  src/NetEvolve.HealthChecks.Firebird/README.md
  src/NetEvolve.HealthChecks.MongoDb/README.md
  src/NetEvolve.HealthChecks.MySql.Connector/README.md
  src/NetEvolve.HealthChecks.MySql/README.md
  src/NetEvolve.HealthChecks.Npgsql/README.md
  src/NetEvolve.HealthChecks.Oracle/README.md
  src/NetEvolve.HealthChecks.Qdrant/README.md
  src/NetEvolve.HealthChecks.RabbitMQ/README.md
  src/NetEvolve.HealthChecks.RavenDb/README.md
  src/NetEvolve.HealthChecks.Redpanda/README.md
  src/NetEvolve.HealthChecks.SQLite.Legacy/README.md
  src/NetEvolve.HealthChecks.SQLite/README.md
  src/NetEvolve.HealthChecks.SqlServer.Legacy/README.md
  src/NetEvolve.HealthChecks.SqlServer/README.md
  src/NetEvolve.HealthChecks/README.md
Labels: state:ready for merge, type:techdebt

#773 chore: Simplified Collection initialization
  tests/NetEvolve.HealthChecks.Tests.Integration/PublicApiTests.cs
Labels: state:ready for merge, type:techdebt

#771 fix: Reduced lambdas and minimized messages
  tests/NetEvolve.HealthChecks.Tests.Integration/MongoDb/MongoDbHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/MongoDb/MongoDbHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/RavenDb/RavenDbHealthCheckTests.cs
Labels: state:ready for merge, type:techdebt

#770 chore: Simplified `HealthCheckTestBase`
  tests/NetEvolve.HealthChecks.Tests.Integration/Internals/HealthCheckTestBase.cs
Labels: state:ready for merge, type:chore

#782 feat: Implementation of the bundle package `NetEvolve.HealthChecks.AWS`
  HealthChecks.sln
  src/NetEvolve.HealthChecks.AWS/NetEvolve.HealthChecks.AWS.csproj
  src/NetEvolve.HealthChecks.AWS/README.md
Labels: state:ready for merge, type:feature

#781 feat: Implementation of the bundle package `NetEvolve.HealthChecks.Azure`
  HealthChecks.sln
  src/NetEvolve.HealthChecks.Azure/NetEvolve.HealthChecks.Azure.csproj
  src/NetEvolve.HealthChecks.Azure/README.md
Labels: state:ready for merge, type:feature

#787 chore: Enabled Publish/Release
  .github/workflows/cicd.yml
Labels: state:ready for merge, type:bug

#789 docs: Minor changes to README
  README.md
Labels: state:ready for merge, type:chore

#790 chore: Updated README script
  scripts/update-readme.ps1
Labels: state:ready for merge, type:chore

#803 fix: Corrected namespace
  tests/NetEvolve.HealthChecks.Tests.Unit/SqlServer.Legacy/SqlServerLegacyOptionsTests.cs
Labels: state:ready for merge, type:bug

#808 chore: Simplified already in use check
  src/NetEvolve.HealthChecks.AWS.SNS/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Abstractions/IHealthChecksBuilderExtensions.cs
  src/NetEvolve.HealthChecks.Apache.ActiveMq/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Apache.Kafka/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.ArangoDb/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Azure.Blobs/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Azure.Queues/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Azure.ServiceBus/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Azure.Tables/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.ClickHouse/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.DB2/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.DuckDB/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Firebird/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Keycloak/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.MongoDb/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.MySql.Connector/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.MySql/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Npgsql/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Odbc/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Oracle/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Qdrant/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.RabbitMQ/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.RavenDb/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Redis/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.Redpanda/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.SQLite.Legacy/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.SQLite/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.SqlServer.Legacy/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.SqlServer/DependencyInjectionExtensions.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/NetEvolve.HealthChecks.Abstractions.PublicApi_HasNotChanged_Theory.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Unit/Abstractions/IHealthChecksBuilderExtensionsTests.cs
Labels: state:ready for merge, type:chore

#818 chore: Use async disposables
  tests/NetEvolve.HealthChecks.Tests.Integration/Internals/HealthCheckTestBase.cs
Labels: state:ready for merge, type:chore

#822 chore: Enabled version ranges for all healthcheck libraries
  src/NetEvolve.HealthChecks.AWS.SNS/NetEvolve.HealthChecks.AWS.SNS.csproj
  src/NetEvolve.HealthChecks.AWS.SQS/NetEvolve.HealthChecks.AWS.SQS.csproj
  src/NetEvolve.HealthChecks.Apache.ActiveMq/NetEvolve.HealthChecks.Apache.ActiveMq.csproj
  src/NetEvolve.HealthChecks.Apache.Kafka/NetEvolve.HealthChecks.Apache.Kafka.csproj
  src/NetEvolve.HealthChecks.ArangoDb/ArangoDbClientProvider.cs
  src/NetEvolve.HealthChecks.ArangoDb/NetEvolve.HealthChecks.ArangoDb.csproj
  src/NetEvolve.HealthChecks.Azure.Blobs/NetEvolve.HealthChecks.Azure.Blobs.csproj
  src/NetEvolve.HealthChecks.Azure.Queues/NetEvolve.HealthChecks.Azure.Queues.csproj
  src/NetEvolve.HealthChecks.Azure.ServiceBus/NetEvolve.HealthChecks.Azure.ServiceBus.csproj
  src/NetEvolve.HealthChecks.Azure.Tables/NetEvolve.HealthChecks.Azure.Tables.csproj
  src/NetEvolve.HealthChecks.ClickHouse/NetEvolve.HealthChecks.ClickHouse.csproj
  src/NetEvolve.HealthChecks.DB2/NetEvolve.HealthChecks.DB2.csproj
  src/NetEvolve.HealthChecks.Dapr/NetEvolve.HealthChecks.Dapr.csproj
  src/NetEvolve.HealthChecks.DuckDB/NetEvolve.HealthChecks.DuckDB.csproj
  src/NetEvolve.HealthChecks.Firebird/NetEvolve.HealthChecks.Firebird.csproj
  src/NetEvolve.HealthChecks.Keycloak/KeycloakClientProvider.cs
  src/NetEvolve.HealthChecks.Keycloak/NetEvolve.HealthChecks.Keycloak.csproj
  src/NetEvolve.HealthChecks.MongoDb/NetEvolve.HealthChecks.MongoDb.csproj
  src/NetEvolve.HealthChecks.MySql.Connector/NetEvolve.HealthChecks.MySql.Connector.csproj
  src/NetEvolve.HealthChecks.MySql/NetEvolve.HealthChecks.MySql.csproj
  src/NetEvolve.HealthChecks.Npgsql/NetEvolve.HealthChecks.Npgsql.csproj
  src/NetEvolve.HealthChecks.Odbc/NetEvolve.HealthChecks.Odbc.csproj
  src/NetEvolve.HealthChecks.Oracle/NetEvolve.HealthChecks.Oracle.csproj
  src/NetEvolve.HealthChecks.Qdrant/NetEvolve.HealthChecks.Qdrant.csproj
  src/NetEvolve.HealthChecks.RabbitMQ/NetEvolve.HealthChecks.RabbitMQ.csproj
  src/NetEvolve.HealthChecks.RavenDb/NetEvolve.HealthChecks.RavenDb.csproj
  src/NetEvolve.HealthChecks.Redis/NetEvolve.HealthChecks.Redis.csproj
  src/NetEvolve.HealthChecks.Redpanda/NetEvolve.HealthChecks.Redpanda.csproj
  src/NetEvolve.HealthChecks.SQLite.Legacy/NetEvolve.HealthChecks.SQLite.Legacy.csproj
  src/NetEvolve.HealthChecks.SQLite/NetEvolve.HealthChecks.SQLite.csproj
  src/NetEvolve.HealthChecks.SqlServer.Legacy/NetEvolve.HealthChecks.SqlServer.Legacy.csproj
  src/NetEvolve.HealthChecks.SqlServer/NetEvolve.HealthChecks.SqlServer.csproj
Labels: state:ready for merge, type:chore

#816 chore: Added base configuration for benchmarks
  HealthChecks.sln
  README.md
  benchmarks/Benchmarks.HealthChecks/Benchmarks.HealthChecks.csproj
  benchmarks/Benchmarks.HealthChecks/Benchmarks/SqlServer.cs
  benchmarks/Benchmarks.HealthChecks/Internals/BenchmarkHealthCheckService.cs
  benchmarks/Benchmarks.HealthChecks/Internals/NetEvolveConfig.cs
  benchmarks/Benchmarks.HealthChecks/Program.cs
  benchmarks/Directory.Build.props
  benchmarks/Directory.Build.targets
  benchmarks/Directory.Packages.props
Labels: state:ready for merge, type:chore

#829 chore: Simplified benchmarks
  benchmarks/Benchmarks.HealthChecks/Benchmarks/SqlServer.cs
  benchmarks/Benchmarks.HealthChecks/Internals/BenchmarkServiceFactory.cs
Labels: state:ready for merge, type:chore

#828 chore: Added `NullLogger` to prevent spam
  tests/NetEvolve.HealthChecks.Tests.Integration/AWS/LocalStackInstance.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Apache.ActiveMq/ActiveMqCustomCredentials.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Apache.ActiveMq/ActiveMqDefaultCredentials.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Apache.ActiveMq/ActiveMqNoCredentials.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Apache.Kafka/KafkaContainer.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/ArangoDb/Container/ContainerBase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.ServiceBus/ServiceBusContainer.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure/AzuriteAccess.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/ClickHouse/ClickHouseDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/DB2/DB2Database.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Firebird/FirebirdDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Keycloak/Container/ContainerBase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/MongoDb/MongoDbDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/MySql/MySqlDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Npgsql/NpgsqlDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Oracle/OracleDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Qdrant/QdrantDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/RabbitMQ/RabbitMQContainer.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/RavenDb/RavenDbDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Redis/RedisContainer.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Redpanda/RedpandaDatabase.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/SqlServer/SqlServerDatabase.cs
Labels: state:ready for merge, type:chore

#835 chore(deps): Bump `Testcontainers.*` to 4.6.0
  Directory.Packages.props
  benchmarks/Benchmarks.HealthChecks/Benchmarks.HealthChecks.csproj
Labels: state:ready for merge, type:chore

#841 chore(deps): Bump Version `NetEvolve.Defaults` to `1.3.115`
  Directory.Packages.props
Labels: state:ready for merge, type:chore

#838 chore(deps): Bump Version `Microsoft.CodeAnalysis.BannedApiAnalyzers`…
  Directory.Packages.props
Labels: state:ready for merge, type:chore

#836 feat: Added `NetEvolve.HealthChecks.AWS.S3` implementation
  Directory.Packages.props
  HealthChecks.slnx
  src/NetEvolve.HealthChecks.AWS.S3/CreationMode.cs
  src/NetEvolve.HealthChecks.AWS.S3/DependencyInjectionExtensions.cs
  src/NetEvolve.HealthChecks.AWS.S3/NetEvolve.HealthChecks.AWS.S3.csproj
  src/NetEvolve.HealthChecks.AWS.S3/README.md
  src/NetEvolve.HealthChecks.AWS.S3/SimpleStorageServiceConfigure.cs
  src/NetEvolve.HealthChecks.AWS.S3/SimpleStorageServiceHealthCheck.cs
  src/NetEvolve.HealthChecks.AWS.S3/SimpleStorageServiceOptions.cs
  src/NetEvolve.HealthChecks.AWS/NetEvolve.HealthChecks.AWS.csproj
  src/NetEvolve.HealthChecks.AWS/README.md
  tests/NetEvolve.HealthChecks.Tests.Architecture/HealthCheckArchitecture.cs
  tests/NetEvolve.HealthChecks.Tests.Architecture/NetEvolve.HealthChecks.Tests.Architecture.csproj
  tests/NetEvolve.HealthChecks.Tests.Integration/AWS.S3/SimpleStorageServiceHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/AWS/LocalStackInstance.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/NetEvolve.HealthChecks.Tests.Integration.csproj
  tests/NetEvolve.HealthChecks.Tests.Integration/PublicApiTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/NetEvolve.HealthChecks.AWS.S3.PublicApi_HasNotChanged_Theory.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/SimpleStorageServiceHealthCheck.AddAWSS3_UseConfiguration_Degraded.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/SimpleStorageServiceHealthCheck.AddAWSS3_UseConfiguration_Healthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/SimpleStorageServiceHealthCheck.AddAWSS3_UseConfiguration_WhenBucketInvalid_Unhealthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/SimpleStorageServiceHealthCheck.AddAWSS3_UseConfiguration_WithAdditionalTags.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/SimpleStorageServiceHealthCheck.AddAWSS3_UseOptionsCreate_Degraded.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/SimpleStorageServiceHealthCheck.AddAWSS3_UseOptionsCreate_Healthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Integration/_snapshots/SimpleStorageServiceHealthCheck.AddAWSS3_UseOptionsCreate_WhenBucketInvalid_Unhealthy.verified.txt
  tests/NetEvolve.HealthChecks.Tests.Unit/AWS.S3/DependencyInjectionExtensionsTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/AWS.S3/SimpleStorageServiceConfigureTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/AWS.S3/SimpleStorageServiceHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/AWS.S3/SimpleStorageServiceOptionsTests.cs
  tests/NetEvolve.HealthChecks.Tests.Unit/NetEvolve.HealthChecks.Tests.Unit.csproj
Labels: state:ready for merge, type:feature

#839 chore(deps): Bump Version `Microsoft.VisualStudio.Threading.Analyzers…
  Directory.Packages.props
Labels: state:ready for merge, type:chore

#840 chore(deps): Bump version `BenchmarkDotNet` to `0.15.2`
  benchmarks/Benchmarks.HealthChecks/Benchmarks.HealthChecks.csproj
Labels: state:ready for merge, type:chore

#844 chore: Centralized SharedType configurations
  tests/NetEvolve.HealthChecks.Tests.Integration/AWS.S3/SimpleStorageServiceHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/AWS.SNS/SimpleNotificationServiceHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/AWS.SQS/SimpleQueueServiceHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Apache.ActiveMq/ActiveMqHealthCustomCredentialsCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Apache.ActiveMq/ActiveMqHealthDefaultCredentialsCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Apache.ActiveMq/ActiveMqHealthNoCredentialsCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Apache.Kafka/KafkaHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/ArangoDb/ArangoDbCustomPasswordHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/ArangoDb/ArangoDbDefaultPasswordHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/ArangoDb/ArangoDbNoPasswordHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.Blobs/BlobContainerAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.Blobs/BlobServiceAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.Queues/QueueClientAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.Queues/QueueServiceAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.ServiceBus/ServiceBusQueueHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.ServiceBus/ServiceBusSubscriptionHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.ServiceBus/ServiceBusTopicHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.Tables/TableClientAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Azure.Tables/TableServiceAvailableHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/ClickHouse/ClickHouseHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/DB2/DB2HealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Firebird/FirebirdHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Internals/InstanceSharedType.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Keycloak/KeycloakCustomCredentialsHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Keycloak/KeycloakDefaultCredentialsHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/MongoDb/MongoDbHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/MySql/MySqlHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/MySqlConnector/MySqlConnectorHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Npgsql/NpgsqlHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Odbc/OdbcSqlServerHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Oracle/OracleHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Qdrant/QdrantHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/RabbitMQ/RabbitMQHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/RavenDb/RavenDbHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Redis/RedisHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/Redpanda/RedpandaHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/SqlServer.Legacy/SqlServerLegacyHealthCheckTests.cs
  tests/NetEvolve.HealthChecks.Tests.Integration/SqlServer/SqlServerHealthCheckTests.cs
Labels: state:ready for merge, type:chore
